### ISSUE TITLE
ugChain - an ecosystem consisting of a series of decentralized applications.

### ISSUE THREAD

**Issue by verfasor** [blockchainedindia/resources#1]
We are currently working on decentralized game account system for Game distribution, Game Prepayment and Prop Purchase.

Demo here: https://ugchaindemo.github.io/
official Org website: ugchain.org 
White-paper: 
[ugChain White Paper_v2.5.pdf](https://github.com/blockchainedindia/resources/files/1463431/ugChain.White.Paper_v2.5.pdf)

**Comment by anistark** [comment]
Interesting @DeadAuthor . Feel free to add your whitepaper as a pull request. Mention this issue # in the PR. 

Additionally, we'll be creating a page dedicated to all the companies and projects on blockchain. I believe, you can add your startup over there as well.
