### ISSUE TITLE
Solidity

### ISSUE THREAD

**Issue by nikhil3000** [blockchainedindia/resources#2]
### Resource Category (Choose from existing categories. If your category is not found, write `Other` followed by the category)
Ethereum and Smart contracts

### Resource along with Link(s) and Author
https://cryptozombies.io/en/course/

### Contributor Name and Gtihub Profile
Nikhil, nikhil3000 
I don't own this content, I am just using it to learn solidity and feel that it should be a part of this wonderful resource list

**Comment by anistark** [comment]
Feel free to open a PR and add your link at the appropriate place. :)

**Comment by anistark** [comment]
Have been added!
