### ISSUE TITLE
Your blockchain resource page

### ISSUE THREAD

**Issue by hellocourage** [blockchainedindia/resources#3]
### Resource Category (Choose from existing categories. If your category is not found, write `Other` followed by the cateogry)
Article
### Resource along with Link(s) and Author
https://www.connectbit.com/blockchain-applications/
### Controbutor Name and Gtihub Profile
Cheefoo, hellocourage

I actually just published a blockchain article on "Blockchain Applications: 58 Killer Ideas For You" :
It might make a good fit for your page. Either way, keep up the awesome work!

**Comment by anistark** [comment]
Feel free to open a PR and add your link at the appropriate place. :)

**Comment by hellocourage** [comment]
Great! :) 

Could you point me on how to open a PR ?

**Comment by anistark** [comment]
Learn more about [PR here](https://help.github.com/articles/about-pull-requests/).

Ideally, you just need to edit the file that you need updated. But since you can't edit it directly, github allows you to fork the repo, edit the file and then send in a pull request back here.

If everything seems right, we'll merge it in.

**Comment by hellocourage** [comment]
I tried and I am stuck at pulling new request. 
http://prntscr.com/j8jwrl

It will be awesome if the article can be added under this category
Article - [Blockchain Applications: Killer Ideas For You
](https://www.connectbit.com/blockchain-applications/)

**Comment by anistark** [comment]
Change your head fork to your repo.

**Comment by anistark** [comment]
Have been added.

**Comment by hellocourage** [comment]
Thanks Kumar! I tried previously, but didn’t work.
