### ISSUE TITLE
HyperLedger

### ISSUE THREAD

**Issue by PPentakotaBC** [blockchainedindia/resources#5]
### Controbutor Name and Gtihub Profile

HyperLedger Fabric - https://hyperledger-fabric.readthedocs.io/en/latest/index.html
One place for all the info of HyperLedger Fabric.

HyperLedger Training & certifications - https://www.hyperledger.org/resources/training

Blockchain council - https://www.blockchain-council.org/certification-training/

**Comment by anistark** [comment]
Feel free to open a Pull Request to add your listings.

**Comment by anistark** [comment]
added
