### ISSUE TITLE
Adding Universal Faucet - multiple network faucet 

### ISSUE THREAD

**Issue by JesseAbram** [blockchainedindia/resources#8]
### Resource Category (Choose from existing categories. If your category is not found, write `Other` followed by the cateogry)
Testnet Faucets
### Resource along with Link(s) and Author
http://faucets.blockxlabs.com
### Controbutor Name and Gtihub Profile
Jesse Abramowitz github - JesseAbram

**Comment by anistark** [comment]
added under faucet https://blockchainedindia.github.io/resources/#faucets
